sudo: false
language: go
env:
  CI_SERVICE: travis-ci
go:
  - 1.7.2
  - tip
install:
  - mkdir -p $GOPATH/src/gopkg.in/googollee
  - ln -s $GOPATH/src/github.com/googollee/go-engine.io $GOPATH/src/gopkg.in/googollee/go-engine.io.v1
  - make getdev
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - make test
  - ./gosweep.sh
