name: Unit tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: 
          - '1.15.x'
          - '1.16.x'
          - 'tip'
    steps:
      - name: Install Go
        if: matrix.go != 'tip'
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Install gotip
        if: matrix.go == 'tip'
        run: |
          git clone --depth=1 https://go.googlesource.com/go $HOME/gotip
          cd $HOME/gotip/src
          ./make.bash
          echo "GOROOT=$HOME/gotip" >> $GITHUB_ENV
          echo "$HOME/gotip/bin" >> $GITHUB_PATH

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Check go version
        run: go version

      - name: Test
        run: make test
